server:
  port: 8079

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/mbr/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service2
          uri: http://localhost:8081/
          predicates:
            - Path=/mbr/**
            - Method=GET,POST
          filters:
            - AuthorizationHeaderFilter
            - RemoveRequestHeader=Cookie



