server:
  port: 8079

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service-Auth
          uri: http://localhost:8081/
          predicates:
            - Path=/mbr/Auth/**
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: user-service2-unAuth
          uri: http://localhost:8081/
          predicates:
            - Path=/mbr/unAuth/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: manager-service-Auth
            uri: http://localhost:8081/
            predicates:
              - Path=/man/Auth/**
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter
        - id: manager-service-unAuth
            uri: http://localhost:8081/
            predicates:
              - Path=/man/unAuth/**
            filters:
              - RemoveRequestHeader=Cookie
        - id: product-service-auth
            uri: http://localhost:8082/
            predicates:
              - Path=/prod/**
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter
        - id: product-service-unauth
            uri: http://localhost:8082/
            predicates:
              - Path=/prd/**
            filters:
              - RemoveRequestHeader=Cookie
        - id: product-service-chat
            uri: http://localhost:8082/
            predicates:
              - Path=/prd/**
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter
        - id: category-service
            uri: http://localhost:8082/
            predicates:
              - Path=/cat/**
            filters:
              - RemoveRequestHeader=Cookie
        - id: complain-service
          uri: http://localhost:8084/
          predicates:
            - Path=/comp/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: blackList-service
            uri: http://localhost:8084/
            predicates:
              - Path=/black/**
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationHeaderFilter



