spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/tiki?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 0197
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.tiki.member.mapper
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
